services:
  frontend:
    build: ./flower-meadow-generator-frontend
    ports: 
      - "8082:80"
    depends_on:
      - "backend"
    volumes:
      - ./flower-meadow-generator-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      my-network:
        aliases:
          - frontend

  backend:
    build: ./flower-meadow-generator-backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      my-network:
        aliases:
          - backend

  db:
    image: "postgres:13.1-alpine"
    restart: always
    container_name: flower-meadow-generator-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: f-m-generator-user
      POSTGRES_PASSWORD: test1234
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/initDatabase.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U f-m-generator-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      my-network:
        aliases:
          - db

networks:
  my-network: