name: Backend CI

on:
  push:
    branches:
      - main
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: f-m-generator-user
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: --name db --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check db container
        run: docker ps
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean package -Dspring.datasource.url=jdbc:postgresql://db:5432/f-m-generator-user
        working-directory: flower-meadow-generator-backend
      - name: Stop PostgreSQL container
        if: always()
        run: docker stop $(docker ps -q)

  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze with Sonar
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=raboro_Flower-Meadow-Generator_Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        working-directory: flower-meadow-generator-backend
