name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependnecies
        run: npm ci
        working-directory: flower-meadow-generator-frontend
      - name: Fix eslint issues
        run: npm run lint-fix
      - name: Commit changes
        run: |
          git config --global user.name 'github-action'
          git config --global user.email 'github-action@github.com'
          git commit -am "fixed eslint issues"
          git push https://$GH_TOKEN_PUSH_LINT_CHANGES@github.com/Raboro/Flower-Meadow-Generator.git HEAD:main
      - name: Run eslint
        run: npm run lint
        working-directory: flower-meadow-generator-frontend
