name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependnecies
        run: npm ci
        working-directory: flower-meadow-generator-frontend
      - name: Fix eslint issues
        run: npm run lint-fix
        working-directory: flower-meadow-generator-frontend
      - name: Commit changes
        run: |
          git config --global user.name ${{secrets.GH_USER_NAME}}
          git config --global user.email ${{secrets.GH_USER_EMAIL}}
          git commit -am "fixed eslint issues"
          git push https://${{ secrets.GH_TOKEN_PUSH_LINT_CHANGES }}@github.com/${{secrets.GH_USER_NAME}}/Flower-Meadow-Generator.git
      - name: Run eslint
        run: npm run lint
        working-directory: flower-meadow-generator-frontend
